MemBuf
NAME
MemBuf
SYNOPSIS
#include <MemBuf.h>
Public Member Functions
MemBuf (int sizebytes=1024)
~MemBuf ()
void resize ()
void rewind ()
void add (const std::string &)
const char * getBufPtr ()
Private Attributes
std::string buffer
Detailed Description
Definition at line 23 of file MemBuf.h.
Constructor & Destructor Documentation
MemBuf::MemBuf (int sizebytes = 1024)
Definition at line 34 of file MemBuf.cpp.
References buffer.
MemBuf::~MemBuf ()
Definition at line 32 of file MemBuf.cpp.
Member Function Documentation
void MemBuf::add (const std::string & buf)
Definition at line 46 of file MemBuf.cpp.
References buffer, and resize().
Referenced by RInside::parseEval().
const char* MemBuf::getBufPtr () [inline]
Definition at line 33 of file MemBuf.h.
References buffer.
Referenced by RInside::parseEval().
void MemBuf::resize ()
Definition at line 38 of file MemBuf.cpp.
References buffer.
Referenced by add().
void MemBuf::rewind ()
Definition at line 42 of file MemBuf.cpp.
References buffer.
Referenced by RInside::parseEval().
Member Data Documentation
std::string MemBuf::buffer [private]
Definition at line 25 of file MemBuf.h.
Referenced by add(), getBufPtr(), MemBuf(), resize(), and rewind().
Author
Generated automatically by Doxygen for RInside from the source code.