.TH "/home/fab/Téléchargements/rinside-master/src/MemBuf.cpp" 3 "Tue Jan 19 2021" "RInside" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/fab/Téléchargements/rinside-master/src/MemBuf.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <string>\fP
.br
\fC#include <MemBuf\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBprogramName\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char* programName"

.PP
Definition at line 32 of file RInside\&.cpp\&.
.PP
Referenced by RInside::initialize(), and RInside::parseEval()\&.
.SS "bool verbose"

.PP
Referenced by RInside::initialize(), logTxtFunction(), RInside::RInside(), and RInside::setVerbose()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RInside from the source code\&.
