.TH "/home/fab/Téléchargements/rinside-master/src/RcppExports.cpp" 3 "Tue Jan 19 2021" "RInside" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/fab/Téléchargements/rinside-master/src/RcppExports.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inst/include/RInside\&.h'\fP
.br
\fC#include <Rcpp\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBshowCompiler\fP ()"
.br
.ti -1c
.RI "RcppExport SEXP \fB_RInside_showCompiler\fP ()"
.br
.ti -1c
.RI "RcppExport void \fBR_init_RInside\fP (DllInfo *dll)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const R_CallMethodDef \fBCallEntries\fP []"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "RcppExport SEXP _RInside_showCompiler ()"

.PP
Definition at line 11 of file RcppExports\&.cpp\&.
.PP
References showCompiler()\&.
.SS "RcppExport void R_init_RInside (DllInfo * dll)"

.PP
Definition at line 24 of file RcppExports\&.cpp\&.
.PP
References CallEntries\&.
.SS "void showCompiler ()"

.PP
Definition at line 5 of file compiler\&.cpp\&.
.PP
Referenced by _RInside_showCompiler()\&.
.SH "Variable Documentation"
.PP 
.SS "const R_CallMethodDef CallEntries[]\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    {"_RInside_showCompiler", (DL_FUNC) &_RInside_showCompiler, 0},
    {NULL, NULL, 0}
}
.fi
.PP
Definition at line 19 of file RcppExports\&.cpp\&.
.PP
Referenced by R_init_RInside()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RInside from the source code\&.
