/home/fab/Téléchargements/rinside-master/src/RInside_C.cpp
NAME
/home/fab/Téléchargements/rinside-master/src/RInside_C.cpp
SYNOPSIS
#include <RInside.h>
Functions
void setupRinC ()
void passToR (SEXP x, char *name)
SEXP evalInR (char *cmd)
void evalQuietlyInR (char *cmd)
void teardownRinC ()
Variables
RInside * rr = NULL
Function Documentation
SEXP evalInR (char * cmd)
Definition at line 36 of file RInside_C.cpp.
References RInside::parseEval(), and rr.
void evalQuietlyInR (char * cmd)
Definition at line 43 of file RInside_C.cpp.
References RInside::parseEvalQ(), and rr.
void passToR (SEXP x, char * name)
Definition at line 31 of file RInside_C.cpp.
References RInside::assign(), and rr.
void setupRinC ()
Definition at line 26 of file RInside_C.cpp.
References rr.
void teardownRinC ()
Definition at line 48 of file RInside_C.cpp.
References rr.
Variable Documentation
RInside* rr = NULL
Definition at line 23 of file RInside_C.cpp.
Referenced by evalInR(), evalQuietlyInR(), passToR(), setupRinC(), and teardownRinC().
Author
Generated automatically by Doxygen for RInside from the source code.