.TH "/home/fab/Téléchargements/rinside-master/inst/include/RInside.h" 3 "Tue Jan 19 2021" "RInside" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/fab/Téléchargements/rinside-master/inst/include/RInside.h
.SH SYNOPSIS
.br
.PP
\fC#include <RInsideCommon\&.h>\fP
.br
\fC#include <Callbacks\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRInside\fP"
.br
.ti -1c
.RI "class \fBRInside::Proxy\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RInside from the source code\&.
