.TH "/home/fab/Téléchargements/rinside-master/src/RInside_C.cpp" 3 "Tue Jan 19 2021" "RInside" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/fab/Téléchargements/rinside-master/src/RInside_C.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <RInside\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsetupRinC\fP ()"
.br
.ti -1c
.RI "void \fBpassToR\fP (SEXP x, char *name)"
.br
.ti -1c
.RI "SEXP \fBevalInR\fP (char *cmd)"
.br
.ti -1c
.RI "void \fBevalQuietlyInR\fP (char *cmd)"
.br
.ti -1c
.RI "void \fBteardownRinC\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRInside\fP * \fBrr\fP = NULL"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "SEXP evalInR (char * cmd)"

.PP
Definition at line 36 of file RInside_C\&.cpp\&.
.PP
References RInside::parseEval(), and rr\&.
.SS "void evalQuietlyInR (char * cmd)"

.PP
Definition at line 43 of file RInside_C\&.cpp\&.
.PP
References RInside::parseEvalQ(), and rr\&.
.SS "void passToR (SEXP x, char * name)"

.PP
Definition at line 31 of file RInside_C\&.cpp\&.
.PP
References RInside::assign(), and rr\&.
.SS "void setupRinC ()"

.PP
Definition at line 26 of file RInside_C\&.cpp\&.
.PP
References rr\&.
.SS "void teardownRinC ()"

.PP
Definition at line 48 of file RInside_C\&.cpp\&.
.PP
References rr\&.
.SH "Variable Documentation"
.PP 
.SS "\fBRInside\fP* rr = NULL"

.PP
Definition at line 23 of file RInside_C\&.cpp\&.
.PP
Referenced by evalInR(), evalQuietlyInR(), passToR(), setupRinC(), and teardownRinC()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RInside from the source code\&.
