.TH "RInside::Proxy" 3 "Tue Jan 19 2021" "RInside" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RInside::Proxy
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RInside\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProxy\fP (SEXP xx)"
.br
.ti -1c
.RI "template<typename T > \fBoperator T\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Rcpp::RObject \fBx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 59 of file RInside\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RInside::Proxy::Proxy (SEXP xx)\fC [inline]\fP"

.PP
Definition at line 61 of file RInside\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > RInside::Proxy::operator T ()\fC [inline]\fP"

.PP
Definition at line 64 of file RInside\&.h\&.
.PP
References x\&.
.SH "Member Data Documentation"
.PP 
.SS "Rcpp::RObject RInside::Proxy::x\fC [private]\fP"

.PP
Definition at line 68 of file RInside\&.h\&.
.PP
Referenced by operator T()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RInside from the source code\&.
