.TH "/home/fab/Téléchargements/rinside-master/src/RInsideEnvVars.h" 3 "Tue Jan 19 2021" "RInside" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/fab/Téléchargements/rinside-master/src/RInsideEnvVars.h
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const char * \fBR_VARS\fP []"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char* R_VARS[]"

.PP
Definition at line 1 of file RInsideEnvVars\&.h\&.
.PP
Referenced by RInside::initialize()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RInside from the source code\&.
