.TH "/home/fab/Téléchargements/rinside-master/src/RInsideAutoloads.h" 3 "Tue Jan 19 2021" "RInside" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/fab/Téléchargements/rinside-master/src/RInsideAutoloads.h
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBpackc\fP = 6"
.br
.ti -1c
.RI "const char * \fBpack\fP []"
.br
.ti -1c
.RI "int \fBpackobjc\fP []"
.br
.ti -1c
.RI "const char * \fBpackobj\fP []"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char* pack[]"
\fBInitial value:\fP
.PP
.nf
= {
        "datasets",
        "utils",
        "grDevices",
        "graphics",
        "stats",
        "methods"
    }
.fi
.PP
Definition at line 2 of file RInsideAutoloads\&.h\&.
.PP
Referenced by RInside::autoloads()\&.
.SS "int packc = 6"

.PP
Definition at line 1 of file RInsideAutoloads\&.h\&.
.PP
Referenced by RInside::autoloads()\&.
.SS "const char* packobj[]"

.PP
Definition at line 18 of file RInsideAutoloads\&.h\&.
.PP
Referenced by RInside::autoloads()\&.
.SS "int packobjc[]"
\fBInitial value:\fP
.PP
.nf
= {
        104,
        215,
        112,
        87,
        449,
        203
    }
.fi
.PP
Definition at line 10 of file RInsideAutoloads\&.h\&.
.PP
Referenced by RInside::autoloads()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RInside from the source code\&.
