.TH "/home/fab/Téléchargements/rinside-master/inst/include/RInsideCommon.h" 3 "Tue Jan 19 2021" "RInside" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/fab/Téléchargements/rinside-master/inst/include/RInsideCommon.h
.SH SYNOPSIS
.br
.PP
\fC#include <RInsideConfig\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <inttypes\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <Rcpp\&.h>\fP
.br
\fC#include <Rembedded\&.h>\fP
.br
\fC#include <R_ext/RStartup\&.h>\fP
.br
\fC#include <MemBuf\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCSTACK_DEFNS\fP"
.br
.ti -1c
.RI "#define \fBHAVE_UINTPTR_T\fP"
.br
.ti -1c
.RI "#define \fBlogTxt\fP(x,  b)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlogTxtFunction\fP (const char *file, const int line, const char *expression, const bool \fBverbose\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CSTACK_DEFNS"

.PP
Definition at line 50 of file RInsideCommon\&.h\&.
.SS "#define HAVE_UINTPTR_T"

.PP
Definition at line 52 of file RInsideCommon\&.h\&.
.SS "#define logTxt(x, b)"

.PP
Definition at line 72 of file RInsideCommon\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void logTxtFunction (const char * file, const int line, const char * expression, const bool verbose)\fC [inline]\fP"

.PP
Definition at line 61 of file RInsideCommon\&.h\&.
.PP
References verbose\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RInside from the source code\&.
