RInside
NAME
RInside
SYNOPSIS
#include <RInside.h>
Classes
class Proxy
Public Member Functions
int parseEval (const std::string &line, SEXP &ans)
void parseEvalQ (const std::string &line)
void parseEvalQNT (const std::string &line)
Proxy parseEval (const std::string &line)
Proxy parseEvalNT (const std::string &line)
template<typename T > void assign (const T &object, const std::string &nam)
RInside ()
RInside (const int argc, const char *const argv[], const bool loadRcpp=true, const bool verbose=false, const bool interactive=false)
~RInside ()
void setVerbose (const bool verbose)
Rcpp::Environment::Binding operator[] (const std::string &name)
void repl ()
Static Public Member Functions
static RInside & instance ()
static RInside * instancePtr ()
Private Member Functions
void init_tempdir (void)
void init_rand (void)
void autoloads (void)
void initialize (const int argc, const char *const argv[], const bool loadRcpp, const bool verbose, const bool interactive)
Private Attributes
MemBuf mb_m
Rcpp::Environment * global_env_m
bool verbose_m
bool interactive_m
Static Private Attributes
static RInside * instance_m = 0
Detailed Description
Definition at line 29 of file RInside.h.
Constructor & Destructor Documentation
RInside::RInside ()
Definition at line 56 of file RInside.cpp.
References initialize().
RInside::RInside (const int argc, const char *const argv[], const bool loadRcpp = true, const bool verbose = false, const bool interactive = false)
Definition at line 98 of file RInside.cpp.
References verbose.
RInside::~RInside ()
Definition at line 43 of file RInside.cpp.
References global_env_m, and instance_m.
Member Function Documentation
template<typename T > void RInside::assign (const T & object, const std::string & nam) [inline]
Definition at line 78 of file RInside.h.
References global_env_m.
Referenced by initialize(), and passToR().
void RInside::autoloads (void) [private]
Definition at line 239 of file RInside.cpp.
References global_env_m, pack, packc, packobj, and packobjc.
Referenced by initialize().
void RInside::init_rand (void) [private]
Definition at line 230 of file RInside.cpp.
Referenced by initialize().
void RInside::init_tempdir (void) [private]
Definition at line 212 of file RInside.cpp.
References setenv().
Referenced by initialize().
void RInside::initialize (const int argc, const char *const argv[], const bool loadRcpp, const bool verbose, const bool interactive) [private]
Definition at line 108 of file RInside.cpp.
References assign(), autoloads(), global_env_m, init_rand(), init_tempdir(), instance_m, interactive_m, programName, R_VARS, setenv(), verbose, and verbose_m.
Referenced by RInside().
RInside & RInside::instance () [static]
Definition at line 416 of file RInside.cpp.
References instance_m.
RInside * RInside::instancePtr () [static]
Definition at line 420 of file RInside.cpp.
References instance_m.
Rcpp::Environment::Binding RInside::operator[] (const std::string & name)
Definition at line 412 of file RInside.cpp.
References global_env_m.
RInside::Proxy RInside::parseEval (const std::string & line)
Definition at line 397 of file RInside.cpp.
References parseEval().
int RInside::parseEval (const std::string & line, SEXP & ans)
Definition at line 326 of file RInside.cpp.
References MemBuf::add(), MemBuf::getBufPtr(), global_env_m, mb_m, programName, MemBuf::rewind(), and verbose_m.
Referenced by evalInR(), parseEval(), parseEvalNT(), parseEvalQ(), and parseEvalQNT().
RInside::Proxy RInside::parseEvalNT (const std::string & line)
Definition at line 406 of file RInside.cpp.
References parseEval().
void RInside::parseEvalQ (const std::string & line)
Definition at line 384 of file RInside.cpp.
References parseEval().
Referenced by evalQuietlyInR().
void RInside::parseEvalQNT (const std::string & line)
Definition at line 392 of file RInside.cpp.
References parseEval().
void RInside::repl ()
Definition at line 424 of file RInside.cpp.
void RInside::setVerbose (const bool verbose) [inline]
Definition at line 88 of file RInside.h.
References verbose, and verbose_m.
Member Data Documentation
Rcpp::Environment* RInside::global_env_m [private]
Definition at line 32 of file RInside.h.
Referenced by assign(), autoloads(), initialize(), operator[](), parseEval(), and ~RInside().
RInside * RInside::instance_m = 0 [static], [private]
Definition at line 44 of file RInside.h.
Referenced by initialize(), instance(), instancePtr(), and ~RInside().
bool RInside::interactive_m [private]
Definition at line 35 of file RInside.h.
Referenced by initialize().
MemBuf RInside::mb_m [private]
Definition at line 31 of file RInside.h.
Referenced by parseEval().
bool RInside::verbose_m [private]
Definition at line 34 of file RInside.h.
Referenced by initialize(), parseEval(), and setVerbose().
Author
Generated automatically by Doxygen for RInside from the source code.