/home/fab/Téléchargements/rinside-master/inst/include/RInside_C.h
NAME
/home/fab/Téléchargements/rinside-master/inst/include/RInside_C.h
SYNOPSIS
#include <Rinternals.h>
Functions
void setupRinC ()
void passToR (SEXP x, char *name)
SEXP evalInR (char *cmd)
void evalQuietlyInR (char *cmd)
void teardownRinC ()
Function Documentation
SEXP evalInR (char * cmd)
Definition at line 36 of file RInside_C.cpp.
References RInside::parseEval(), and rr.
void evalQuietlyInR (char * cmd)
Definition at line 43 of file RInside_C.cpp.
References RInside::parseEvalQ(), and rr.
void passToR (SEXP x, char * name)
Definition at line 31 of file RInside_C.cpp.
References RInside::assign(), and rr.
void setupRinC ()
Definition at line 26 of file RInside_C.cpp.
References rr.
void teardownRinC ()
Definition at line 48 of file RInside_C.cpp.
References rr.
Author
Generated automatically by Doxygen for RInside from the source code.