.TH "/home/fab/Téléchargements/rinside-master/src/setenv/setenv.c" 3 "Tue Jan 19 2021" "RInside" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/fab/Téléchargements/rinside-master/src/setenv/setenv.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsetenv\fP (const char *env_var, const char *env_val, int dummy)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int setenv (const char * env_var, const char * env_val, int dummy)"

.PP
Definition at line 28 of file setenv\&.c\&.
.PP
Referenced by RInside::init_tempdir(), and RInside::initialize()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RInside from the source code\&.
